### ISSUE TITLE
Support multiple endpoints for memecache sampler

### ISSUE THREAD

**Issue by eaddingtonwhite** [twitter/rezolus#237]
Currently the memcache sampler in Rezolus only supports passing a single Memcache endpoint to monitor and sample
https://github.com/twitter/rezolus/blob/master/src/config/samplers.rs#L93
https://github.com/twitter/rezolus/blob/fadf6f8eba44002dc51911ca738f63b432f620b0/src/samplers/memcache/mod.rs#L43-L57

It would be nice if we could pass a comma separated list of `host:port` memcache endpoints to Rezolus memcache sampler. This would allow you to run a single Rezolus agent to monitor multiple Memcache process or containers on a single host. The config might look something like this:

```toml
# An example config that produces percentile metrics for specific Memcached stats
# while preserving the original metric names.

[general]
listen = "0.0.0.0:4242"
fault_tolerant = false
reading_suffix = ""

[samplers]
[samplers.memcache]
enabled = true
endpoint = "localhost:11211,localhost:11212,localhost:11213,localhost:11214"
``` 

An alternative would be to run a Rezolus agent per memcache process 1:1 but this creates additional overhead for end user to configure and run on host in this way.
